"""Initial migration

Revision ID: aa44f38e7d08
Revises: 
Create Date: 2026-04-08 23:11:26.674396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa44f38e7d08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('momento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('alvo', sa.String(), nullable=True),
    sa.Column('detalhe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_momento'), 'auditoria', ['momento'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario'), 'auditoria', ['usuario'], unique=False)
    op.create_table('catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linha', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_id'), 'catalogo', ['id'], unique=False)
    op.create_table('inspecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('soldador', sa.String(), nullable=True),
    sa.Column('processo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('defeitos', sa.String(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('fotos', sa.String(), nullable=True),
    sa.Column('assinatura', sa.String(), nullable=True),
    sa.Column('reinspeção_de', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reinspeção_de'], ['inspecoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspecoes_data'), 'inspecoes', ['data'], unique=False)
    op.create_index(op.f('ix_inspecoes_id'), 'inspecoes', ['id'], unique=False)
    op.create_index(op.f('ix_inspecoes_os'), 'inspecoes', ['os'], unique=False)
    op.create_table('soldadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_soldadores_id'), 'soldadores', ['id'], unique=False)
    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('momento', sa.String(), nullable=False),
    sa.Column('sucesso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentativas_login_id'), 'tentativas_login', ['id'], unique=False)
    op.create_index(op.f('ix_tentativas_login_usuario'), 'tentativas_login', ['usuario'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hash_senha', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('papel', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tentativas_login_usuario'), table_name='tentativas_login')
    op.drop_index(op.f('ix_tentativas_login_id'), table_name='tentativas_login')
    op.drop_table('tentativas_login')
    op.drop_index(op.f('ix_soldadores_id'), table_name='soldadores')
    op.drop_table('soldadores')
    op.drop_index(op.f('ix_inspecoes_os'), table_name='inspecoes')
    op.drop_index(op.f('ix_inspecoes_id'), table_name='inspecoes')
    op.drop_index(op.f('ix_inspecoes_data'), table_name='inspecoes')
    op.drop_table('inspecoes')
    op.drop_index(op.f('ix_catalogo_id'), table_name='catalogo')
    op.drop_table('catalogo')
    op.drop_index(op.f('ix_auditoria_usuario'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_momento'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
